networks:
    cloud:
        name: cloud
        driver: bridge

services:
    erasmusbot:
        container_name: erasmusbot
        build:
            context: ./
        volumes:
            - ./:/app
        environment:
            FLASK_ENV: production
        ports:
            - "5000:5000"
        networks:
            - cloud
        restart: always
